export enum ROUTES {
  root = '/',
  signUp = '/signUp',
  signIn = '/signIn',
  profile = '/profile',
  projects = '/projects',
  project = '/:projectId',
  boards = '/boards',
  addBoard = '/add_boards',
  devices = '/devices',
  sensors = '/sensors',
  firmware = '/frimware',
  dashboards = '/dashboards',
  virtualDashboards = '/virtual_dashboards',
  management = '/user_management',
  settings = '/settings',
}
